### ISSUE TITLE
`makeplots` not working

### ISSUE THREAD

**Issue by asjadnaqvi** [thegland/wooldid#1]
Thank you for putting together this exciting package! The `makeplots` option is not returning an event plot. 

Additionally, is it possible to get event study estimates stored in some e-class matrix?

**Comment by thegland** [comment]
Thanks for reaching out with any bugs you may have found! Could you share some information about the circumstances in which makeplots is not working? Sample code with a test dataset where I can replicate your problem would be very helpful.

The event study estimates, if requested, should end up being returned in an e-class matrix as things are -- they should show up if you a command like esttab to present wooldid's output. The variance covariance matrix returned will be a bit wonky (the off diagonal elements will artificially be set to 0), but this shouldn't be an issues if used just for compatibility with table production tools and the like.

**Comment by asjadnaqvi** [comment]
The code I used is below. I am updating the [DiD packages](https://github.com/asjadnaqvi/DiD) page and would like to include `wooldid` with the next release. Any help on getting the command running, or getting outputs to be able to pass it onto other [graph commands](https://asjadnaqvi.github.io/DiD/docs/code/06_combined/) would be highly appreciated!


```
clear

**** installation
net install wooldid, from("https://raw.githubusercontent.com/thegland/wooldid/main/wooldidinstall/") replace

*ssc install wooldid, replace
*which wooldid  // missing information on package (returns a null)


*** data generation
local units = 30
local start = 1
local end = 60

local time = `end' - `start' + 1
local obsv = `units' * `time'
set obs `obsv'

egen id	   = seq(), b(`time')  
egen t 	   = seq(), f(`start') t(`end') 	

sort  id t
xtset id t

set seed 20211222

gen Y 	   		= 0		// outcome variable	
gen D 	   		= 0		// intervention variable
gen cohort      = .  	// treatment cohort
gen effect      = .		// treatment effect size
gen first_treat = .		// when the treatment happens for each cohort
gen rel_time	= .     // time - first_treat

levelsof id, local(lvls)
foreach x of local lvls {
	local chrt = runiformint(0,5)	
	replace cohort = `chrt' if id==`x'
}


levelsof cohort , local(lvls)  //  if cohort!=0 skip cohort 0 (never treated)
foreach x of local lvls {
	
	local eff = runiformint(2,10)
		replace effect = `eff' if cohort==`x'
			
	local timing = runiformint(`start',`end' + 20)	// 
	replace first_treat = `timing' if cohort==`x'
	replace first_treat = . if first_treat > `end'
		replace D = 1 if cohort==`x' & t>= `timing' 
}

replace rel_time = t - first_treat
replace Y = id + t + cond(D==1, effect * rel_time, 0) + rnormal()

gen gvar = first_treat
recode gvar (. = 0)

gen never_treat = first_treat==.  // never treated group


*** data graph
*xtline Y, overlay legend(off)


*** test the command
wooldid Y id t first_treat, cluster(id) makeplots
```

**Comment by thegland** [comment]
Thank you for providing that example!

To produce event study plots, you also need to specify the number of relative year-specific effects that you want estimated. You can do this by specifying the options espre(X) and espost(Y) to get X pre-treatment effects and Y post-treatment effects.

So, changing the wooldid command in your code to the following should generate an event study plot:
`wooldid Y id t first_treat, cluster(id) makeplots espre(2) espost(2)
`

Hope that helps!
